version: '3.1'

services:

  wordpress:
    container_name: cms-wordpress-web
    image: gekal/wordpress:php8.2-apache
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - cms-wordpress-web:/var/www/html

  db:
    container_name: cms-wordpress-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./wordpress/db/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./wordpress/db/initdb:/docker-entrypoint-initdb.d/:ro
      # - ./wordpress/db/data:/var/lib/mysql
      - cms-wordpress-db:/var/lib/mysql
volumes:
  cms-wordpress-web:
  cms-wordpress-db:
